import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {PGlite} from '@electric-sql/pglite';import {quizMatch,quizScore,newsMatches,botChoice,draftTeam} from '../public/game-core.js';import {draftClock} from '../public/draft-clock.js';import {validateAction} from '../lib/community.js';
test('five unique quiz targets and streak scoring',()=>{const ps=Array.from({length:15},(_,i)=>({id:String(i),name:'Player '+i}));const rounds=quizMatch(ps);assert.equal(rounds.length,5);assert.equal(new Set(rounds.map(r=>r.target.id)).size,5);assert.deepEqual(quizScore([true,true,false,true,true]),{hits:4,streak:2,bestStreak:2,points:460});assert.equal(quizScore([true,true,true,true,true]).points,650);assert.equal(quizScore([false,false,false,false,false]).points,0);assert.equal(quizMatch(ps.slice(0,4)).length,0)});
test('draft clock schedules one pick, ignores canceled callbacks and resumes',()=>{const jobs=[];let steps=0;const clock=draftClock(()=>steps++,{schedule:fn=>(jobs.push(fn),jobs.length),cancel:()=>{},delay:1});clock.start();clock.start();assert.equal(jobs.length,1);clock.stop();jobs[0]();assert.equal(steps,0);clock.start();jobs[1]();assert.equal(steps,1);assert.equal(clock.pending,false)});
test('news prioritizes full player name, normalizes apostrophes, avoids substring collisions',()=>{const f=[{name:"Ja'Marr Chase"},{name:'Josh Allen'},{name:'Mike Evans'}];assert.equal(newsMatches({title:'Ja’Marr Chase injury update'},f)[0].name,"Ja'Marr Chase");assert.equal(newsMatches({title:'Josh Allenby is back'},f).length,0);assert.equal(newsMatches({title:'NFL updates',description:'Josh Allen returns to practice'},f)[0].name,'Josh Allen')});
test('bots respect ADP value and fill starter needs without duplicate picks',()=>{const pool=Array.from({length:600},(_,i)=>({id:String(i),adp:i+1,position:['RB','WR','QB','TE','K','DEF'][i%6]}));let picks=[];for(let n=0;n<4*9;n++){const p=botChoice(pool,picks,4,9);assert.ok(p);picks.push(p)}assert.equal(new Set(picks.map(p=>p.id)).size,36);for(let t=0;t<4;t++){const mine=picks.filter((_,i)=>draftTeam(i,4)===t);for(const [pos,min]of [['QB',1],['RB',2],['WR',2],['TE',1],['K',1],['DEF',1]])assert.ok(mine.filter(p=>p.position===pos).length>=min)}});
test('personal records are isolated, idempotent, bounded and only accessible to verified accounts',async()=>{
 const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);
 await db.exec(fs.readFileSync(new URL('../community-schema.sql',import.meta.url),'utf8'));await db.exec(fs.readFileSync(new URL('../personal-schema.sql',import.meta.url),'utf8'));
 const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';await db.query('insert into auth.users values($1,now()),($2,now())',[a,b]);const as=async(u,sql,args=[])=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.exec('set role authenticated');return (await db.query(sql,args)).rows[0]?.d};
 let d=await as(a,'select public.zona_favorite($1,false) as d',[{id:'123',name:'Josh Allen',position:'QB',team:'BUF'}]);assert.equal(d.favorites.length,1);
 d=await as(b,'select public.zona_personal() as d');assert.equal(d.favorites.length,0);
 const run='33333333-3333-4333-8333-333333333333';await as(a,'select public.zona_quiz_result($1,4,2,460)',[run]);d=await as(a,'select public.zona_quiz_result($1,4,2,460) as d',[run]);assert.equal(d.games,1);assert.equal(d.bestPoints,460);
 d=await as(a,"select public.zona_quiz_result('44444444-4444-4444-8444-444444444444',1,1,110) as d");assert.equal(d.games,2);assert.equal(d.bestPoints,460);
 await assert.rejects(as(a,'select public.zona_quiz_result($1,8,8,9999)',[run]),/inválido/);await assert.rejects(as(b,'select * from zona_private.personal'),/permission denied/);
 d=await as(a,'select public.zona_favorite($1,true) as d',[{id:'123',name:'Josh Allen'}]);assert.equal(d.favorites.length,0);
 await db.exec('reset role;set role anon');await assert.rejects(db.query('select public.zona_personal()'),/permission denied/);await db.close();
});
test('personal endpoint inputs discard supplied owner and reject invalid mutations',()=>{const rpc=validateAction('favorite',{userId:'someone-else',player:{id:'1',name:'Josh Allen',userId:'other'},remove:false});assert.equal(rpc[1].userId,undefined);assert.equal(rpc[1].p_player.userId,undefined);assert.throws(()=>validateAction('favorite',{player:{id:'1',name:'Josh'},remove:'yes'}));assert.throws(()=>validateAction('quiz',{run:'invalid',hits:5,streak:5,points:650}))});
