import {TEAMS} from './teams.js';
import {POSITIONS,score,out,advice} from './scoring.js';
const cache=new Map(),pending=new Map();const alias=t=>({WSH:'WAS',JAX:'JAC',LA:'LAR'}[t]||t);
async function source(key,url,ttl,transform=x=>x,text=false){const previous=cache.get(key);if(previous&&Date.now()-previous.time<ttl)return {...previous,stale:false};if(pending.has(key))return pending.get(key);const work=(async()=>{try{const r=await fetch(url,{signal:AbortSignal.timeout(16000)});if(!r.ok)throw Error('HTTP '+r.status);const entry={value:transform(text?await r.text():await r.json()),time:Date.now(),url};cache.set(key,entry);if(cache.size>50)cache.delete(cache.keys().next().value);return {...entry,stale:false}}catch(e){if(previous&&Date.now()-previous.time<86400000)return {...previous,stale:true};throw e}finally{pending.delete(key)}})();pending.set(key,work);return work}
function csvLine(s){const a=[];let v='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(c==='"'){if(q&&s[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){a.push(v);v=''}else v+=c}a.push(v);return a}
export function parseGames(csv){const [h,...lines]=csv.trim().split(/\r?\n/),heads=csvLine(h);const games=lines.map(l=>Object.fromEntries(csvLine(l).map((v,i)=>[heads[i],v]))).filter(r=>r.season==='2026'&&r.game_type==='REG').map(r=>{const offset=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',timeZoneName:'shortOffset'}).formatToParts(new Date(r.gameday+'T12:00:00Z')).find(x=>x.type==='timeZoneName')?.value==='GMT-4'?'-04:00':'-05:00';return {week:Number(r.week),home:alias(r.home_team),away:alias(r.away_team),date:r.gametime?new Date(r.gameday+'T'+r.gametime+':00'+offset).toISOString():null,venue:r.stadium,neutral:r.location==='Neutral',homeScore:r.home_score===''?null:Number(r.home_score),awayScore:r.away_score===''?null:Number(r.away_score)}});if(games.length!==272)throw Error('Calendario incompleto');return games}
export function parseESPN(all){const rows=all.flatMap(d=>d.events||[]).filter(e=>e.season?.year===2026&&e.season?.type===2);const unique=new Map(rows.map(e=>[e.id,e]));const games=[...unique.values()].map(e=>{const c=e.competitions[0],h=c.competitors.find(t=>t.homeAway==='home'),a=c.competitors.find(t=>t.homeAway==='away'),done=c.status?.type?.completed||e.status?.type?.completed;return {week:Number(e.week.number),home:alias(h.team.abbreviation),away:alias(a.team.abbreviation),date:e.date,venue:c.venue?.fullName||'',neutral:!!c.neutralSite,homeScore:done?Number(h.score):null,awayScore:done?Number(a.score):null}});if(games.length!==272)throw Error('Calendario incompleto');return games}
async function espnSchedule(){const years=await Promise.all([2026,2027].map(y=>source('espn-calendar-'+y,`https://site.api.espn.com/apis/site/v2/sports/football/nfl/scoreboard?dates=${y}&seasontype=2&limit=1000`,300000)));return {value:parseESPN(years.map(y=>y.value)),time:Math.min(...years.map(y=>y.time)),url:'https://www.espn.com/nfl/schedule',stale:years.some(y=>y.stale)}}
const gameState=g=>g.homeScore!=null&&g.awayScore!=null?'final':g.date&&Date.parse(g.date)<Date.now()?'started':'pre';
const teamGame=(games,team,week)=>{const g=games.find(g=>g.week===week&&(g.home===team||g.away===team));return g?{...g,opponent:g.home===team?g.away:g.home,isHome:g.home===team,state:gameState(g)}:null};
function records(rows,week,kind){if(!Array.isArray(rows))throw Error('Respuesta de estadísticas inválida');const map=new Map;for(const x of rows){if(Number(x.season)!==2026||Number(x.week)!==week||x.season_type!=='regular'||x.category!==kind||!POSITIONS.includes(x.player?.position))continue;const id=String(x.player_id),old=map.get(id);if(!old||kind==='proj'&&x.company==='rotowire'&&old.company!=='rotowire'||x.company===old.company&&Number(x.updated_at)>Number(old.updated_at))map.set(id,x)}return [...map.values()]}
export async function getBoard(requested){const warnings=[],sources=[];const note=(label,x)=>{sources.push({label,date:new Date(x.time).toISOString(),url:x.url,stale:x.stale});if(x.stale)warnings.push(label+': se muestra una consulta anterior.')};
const state=await source('state','https://api.sleeper.app/v1/state/nfl',60000);note('Semana NFL',state);const currentWeek=Number(state.value.season)>2026?18:Number(state.value.season)<2026?1:Math.max(1,Math.min(18,Number(state.value.week)||1));const week=requested||currentWeek;
const [catalog,schedule,projection]=await Promise.allSettled([
 source('players','https://api.sleeper.app/v1/players/nfl',86400000,x=>{if(!x||Object.keys(x).length<100)throw Error('Catálogo inválido');return x}),
 espnSchedule(),
 source('proj'+week,`https://api.sleeper.app/projections/nfl/2026/${week}?season_type=regular&position[]=QB&position[]=RB&position[]=WR&position[]=TE&position[]=K&position[]=DEF`,300000,x=>records(x,week,'proj'))]);
if(catalog.status!=='fulfilled')throw Error('No se pudo cargar el catálogo NFL.');note('Catálogo',catalog.value);const games=schedule.status==='fulfilled'?schedule.value.value:[];if(schedule.status==='fulfilled')note('Calendario y resultados',schedule.value);else warnings.push('Calendario no disponible: no se confirmarán descansos ni partidos finalizados.');const projections=projection.status==='fulfilled'?projection.value.value:[];if(projection.status==='fulfilled')note('Proyecciones semanales',projection.value);else warnings.push('Proyecciones no disponibles.');
const maxWeek=Math.min(week,currentWeek),historyRows=[];for(let start=1;start<=maxWeek;start+=4){const ws=Array.from({length:Math.min(4,maxWeek-start+1)},(_,i)=>start+i);const batch=await Promise.allSettled(ws.map(w=>source('stats'+w,`https://api.sleeper.app/stats/nfl/2026/${w}?season_type=regular`,w<currentWeek?3600000:60000,x=>records(x,w,'stat'))));batch.forEach((r,i)=>{if(r.status==='fulfilled'){historyRows.push(...r.value.value);note('Resultados semana '+ws[i],r.value)}else warnings.push('Resultados semana '+ws[i]+' no disponibles.')})}
const histories=new Map,allowed=new Map;const catalogRaw=catalog.value.value;
for(const r of historyRows){const pos=r.player.position,calc=score(r.stats,pos);const team=alias(r.team),g=teamGame(games,team,Number(r.week)),final=g?.state==='final';const entry={week:Number(r.week),team,opponent:alias(r.opponent),points:calc?.points??null,final:!!final,stats:r.stats};if(!histories.has(String(r.player_id)))histories.set(String(r.player_id),[]);histories.get(String(r.player_id)).push(entry);
 if(final&&Number(r.week)<week&&calc&&r.opponent){const key=alias(r.opponent)+'|'+pos+'|'+r.week;allowed.set(key,(allowed.get(key)||0)+calc.points)}}
const allowedFor=(team,pos)=>{const entries=[...allowed].filter(([k])=>k.startsWith(team+'|'+pos+'|')).map(([,n])=>n);return entries.length?{average:entries.reduce((a,b)=>a+b,0)/entries.length,games:entries.length}:null};
const info=Object.fromEntries(Object.entries(TEAMS).map(([code,name])=>[code,{code,name,wins:0,losses:0,ties:0,played:0,pointsFor:0,pointsAgainst:0}]));for(const g of games.filter(g=>gameState(g)==='final'))for(const [t,a,b] of [[g.home,g.homeScore,g.awayScore],[g.away,g.awayScore,g.homeScore]]){const x=info[t];x.played++;x.pointsFor+=a;x.pointsAgainst+=b;if(a>b)x.wins++;else if(a<b)x.losses++;else x.ties++}
const pm=new Map(projections.map(p=>[String(p.player_id),p]));const ids=new Set(Object.values(catalogRaw).filter(p=>p.active&&p.team&&POSITIONS.includes(p.position)).map(p=>String(p.player_id)));for(const r of historyRows.filter(r=>Number(r.week)===week))ids.add(String(r.player_id));
const players=[...ids].map(id=>{const c=catalogRaw[id]||{},history=(histories.get(id)||[]).sort((a,b)=>a.week-b.week),actual=history.find(h=>h.week===week),pr=pm.get(id);const position=c.position||pr?.player?.position;const historical=week<currentWeek&&actual;const team=historical?actual.team:alias(c.team||pr?.team);const g=teamGame(games,team,week);const bye=games.length===272&&!g;const valid=pr&&alias(pr.team)===team;const calc=valid&&!bye?score(pr.stats,position):null;const recent=history.filter(h=>h.final&&h.week<week&&h.points!=null).slice(-3);return {id,gsisId:c.gsis_id||null,bio:{birth:c.birth_date,college:c.college,height:c.height,weight:c.weight,number:c.number,experience:c.years_exp},name:position==='DEF'?(TEAMS[team]||team)+' D/ST':c.full_name||[c.first_name,c.last_name].filter(Boolean).join(' ')||id,position,team,injury:valid&&pr.player&&Object.hasOwn(pr.player,'injury_status')?pr.player.injury_status:(c.injury_status||null),game:g,bye,opponent:g?.opponent||(bye?null:alias(pr?.opponent)),points:calc?.points??null,parts:calc?.parts??null,stats:valid?pr.stats:{},actual:actual?.points??null,actualFinal:!!actual?.final,history,recentAverage:recent.length?recent.reduce((t,h)=>t+h.points,0)/recent.length:null,recentGames:recent.length,matchup:allowedFor(g?.opponent,position),provider:pr?.company||null,projectionUpdated:pr?.updated_at?new Date(pr.updated_at).toISOString():null}}).filter(p=>POSITIONS.includes(p.position)&&p.team);
players.sort((a,b)=>(b.points??-999)-(a.points??-999));const ranks={};for(const p of players){p.posRank=p.points!=null&&!p.bye&&!(week===currentWeek&&out(p))?(ranks[p.position]=(ranks[p.position]||0)+1):null;p.advice=advice(p,week,currentWeek)}
return {season:2026,week,currentWeek,retrievedAt:new Date().toISOString(),games,players,teamInfo:info,warnings,sources,stale:sources.some(x=>x.stale)};
}
export async function getNews(){const x=await source('news','https://site.api.espn.com/apis/site/v2/sports/football/nfl/news',1800000);if(!Array.isArray(x.value.articles))throw Error('Noticias inválidas');return {date:new Date(x.time).toISOString(),stale:x.stale,articles:x.value.articles.map(n=>({title:n.headline,date:n.published,url:n.links?.web?.href})).filter(n=>/^https:\/\/([a-z0-9-]+\.)?espn\.com\//i.test(n.url))}}
export async function getDraft(){const x=await source('season-adp','https://api.sleeper.app/projections/nfl/2026?season_type=regular&position[]=QB&position[]=RB&position[]=WR&position[]=TE&position[]=K&position[]=DEF',3600000);const map=new Map;for(const r of x.value){if(r.company!=='rotowire'||r.week!=null||Number(r.season)!==2026||!POSITIONS.includes(r.player?.position)||!r.team)continue;const adp=Number(r.stats?.adp_ppr);if(!Number.isFinite(adp)||adp<=0||adp>=999)continue;const id=String(r.player_id);map.set(id,{id,name:r.player.position==='DEF'?(TEAMS[alias(r.team)]||r.team)+' D/ST':[r.player.first_name,r.player.last_name].filter(Boolean).join(' '),position:r.player.position,team:alias(r.team),adp,points:score(r.stats,r.player.position)?.points??null})}const players=[...map.values()].sort((a,b)=>a.adp-b.adp);if(players.length<250)throw Error('Draft incompleto');return {players,date:new Date(x.time).toISOString(),stale:x.stale,season:2026}}
